import java.util.Scanner;

//Start of code borrowed from Sample Code Facial Recognition APP with OPP
class Photo {
    int measureA, measureB, measureC, measureD, measureE, measureF;
    String name;
    String digSig;

    // Constructor
    Photo(String name, int measureA, int measureB, int measureC, int measureD, int measureE,
    		int measureF) {
        this.name = name;
        this.measureA = measureA;
        this.measureB = measureB;
        this.measureC = measureC;
        this.measureD = measureD;
        this.measureE = measureE;
        this.measureF = measureF;
        computeSig();
    }

    void computeSig() {
    	//Starting point of code edited by ChatGPT
        // Create 15 ratios and round them to four digits
        double[] ratios = new double[15];
        for (int i = 0; i < 15; i++) {
            switch (i) {
                case 0:  
                    ratios[i] = (double) measureA / measureB;
                    break;
                case 1:  
                    ratios[i] = (double) measureA / measureC;
                    break;
                case 2: 
                    ratios[i] = (double) measureA / measureD;
                    break;
                case 3: 
                    ratios[i] = (double) measureA / measureE;
                    break;
                case 4: 
                    ratios[i] = (double) measureA / measureF;
                    break;
                case 5: 
                    ratios[i] = (double) measureB / measureC;
                    break;
                case 6: 
                    ratios[i] = (double) measureB / measureD;
                    break;
                case 7: 
                    ratios[i] = (double) measureB / measureE;
                    break;
                case 8: 
                    ratios[i] = (double) measureB / measureF;
                    break;
                case 9: 
                    ratios[i] = (double) measureC / measureD;
                    break;
                case 10: 
                    ratios[i] = (double) measureC / measureE;
                    break;
                case 11: 
                    ratios[i] = (double) measureC / measureF;
                    break;
                case 12:
                    ratios[i] = (double) measureD / measureE;
                    break;
                case 13: 
                    ratios[i] = (double) measureD / measureF;
                    break;
                case 14: 
                    ratios[i] = (double) measureE / measureF;
                    break;
            }
        }

        // Create a string of size 60 from those digits
        StringBuilder sigBuilder = new StringBuilder();
        for (int i = 0; i < 15; i++) {
            String ratioStr = String.format("%.4f", ratios[i]);
            sigBuilder.append(ratioStr);
        }
        digSig = sigBuilder.toString();
    }

    String getDigSig() {
        return this.digSig;
    }

    double compare(String anotherDigSig) {
        double totalMatch = 0;
        for (int i = 0; i < 15; i++) {
            // Get the five characters from digSig
            String str1 = digSig.substring(i * 4, (i * 4) + 4);
            // Convert to a double
            double r = Double.parseDouble(str1);

            // Get the five characters from anotherDigSig
            String str2 = anotherDigSig.substring(i * 4, (i * 4) + 4);
            // Convert to a double
            double s = Double.parseDouble(str2);
            
            // Compute percent match for that ratio
            double m = -Math.abs(Math.log(r / s) / Math.log(2)) + 1;
            totalMatch += m;
        }

        // Calculate and return the average match
        return totalMatch / 15;
    }
}
		//End of code edited by ChatGPT
public class JavaSoundsLikeCoffee {
    static Scanner userinput = new Scanner(System.in);

    public static void main(String[] args) {
        Photo[] myphoto = new Photo[5];
        myphoto[0] = new Photo("Cody", 124, 138, 56, 50, 35, 31);
        myphoto[1] = new Photo("Julien", 131 , 116 , 48, 45, 36, 38);
        myphoto[2] = new Photo("Michael", 135, 99, 55, 47, 40, 37);
        myphoto[3] = new Photo("Matthew", 101, 125, 30, 48, 35, 32);
        myphoto[4] = new Photo("Santa", 135, 155, 40, 53, 57, 37);

        int[] m = new int[6]; // Measurement array
        double[] match = new double[5]; // Match array

        for (int i = 0; i < 6; i++) {
            System.out.println("Enter measurement #" + i + ":");
            m[i] = userinput.nextInt();
        }

        Photo mystery = new Photo("unknown", m[0], m[1], m[2], m[3], m[4], m[5]);
        String mysteryDigSig = mystery.getDigSig();
        
        //Starting point of code generated by ChatGPT
        //Value between 0 and 1 to get percents
        double maxMatch = 0;
        int bestMatchIndex = -1;
        //Check for best match
        for (int i = 0; i < 5; i++) {
            match[i] = myphoto[i].compare(mysteryDigSig);
            if (match[i] > maxMatch) {
                maxMatch = match[i];
                bestMatchIndex = i;
            }
        }

        if (bestMatchIndex != -1) {
            System.out.println("The closest match is: " + myphoto[bestMatchIndex].name);
            //Formatting final results
            Double finalPercent = maxMatch * 100;
            String formatter = String.format("%.3f", finalPercent);
            System.out.println("Match Percentage: " + formatter + "%");
        } else {
            System.out.println("No match found.");
        }
    
    }
}

